---
- name: Install dnsmasq
  package:
    name: dnsmasq
    state: present
  tags:
    - dns

- name: Setup dnsmasq.conf from template
  template:
    src: dnsmasq.conf
    dest: /etc/dnsmasq.conf
  notify: restart dnsmasq

- name: Gather network facts from all hosts in inventory
  setup:
    gather_subset:
      - '!all'
      - '!min'
      - network
  delegate_to: "{{ item }}"
  delegate_facts: True
  loop: "{{ groups['all'] }}"
  tags:
    - hosts

- name: Generate /etc/hosts with all hosts from inventory
  template:
    src: hosts.j2
    dest: /etc/hosts
  tags:
    - hosts
  notify: reload dnsmasq
